@startuml
hide circle
hide empty members
left to right direction
skinparam monochrome true

class Fraction {
  numerator: int
  denominator: int
  print(self): None
  add(self, other: Fraction): None

}

@enduml